package web

var enTranslations = map[string]string{
		"language.label":             "Language",
		"language.english":           "English",
		"language.russian":           "Russian",
		"title.access_denied":        "Access denied",
		"title.selection":            "Route selection",
		"title.login":                "Login",
		"title.admin":                "Administration",
		"title.user":                 "User %s",
		"access_denied.heading":      "Access denied",
		"admin.heading":              "Administration",
		"admin.link":                 "Administration",
		"bgp.established":            "BGP session established",
		"bgp.unknown":                "BGP state unknown",
		"debug.heading":              "CIDR diagnostics",
		"debug.description":          "Inspect which enabled catalog services and user selections cover an IP address or subnet. User coverage is shown before and after effective route allow/deny filters.",
		"debug.input":                "IP address or CIDR",
		"debug.submit":               "Analyze",
		"debug.results":              "Coverage diagnostics",
		"debug.full_services":        "Services with full coverage",
		"debug.partial_services":     "Services with partial coverage",
		"debug.combined":             "Combined service coverage",
		"debug.users":                "Enabled users with matching selections",
		"debug.no_matches":           "No matching enabled services or users.",
		"debug.no_items":             "None",
		"debug.coverage":             "coverage",
		"debug.before_filters":       "before filters",
		"debug.after_filters":        "after filters",
		"debug.close":                "Close",
		"debug.request_failed":       "Could not analyze this CIDR.",
		"catalog.mode":               "Catalog mode",
		"catalog.modes":              "Catalog modes",
		"catalog.modes_hint":         "Only enabled modes can be selected by users or used for announcements and diagnostics.",
		"catalog.key":                "Key",
		"catalog.category":           "Category",
		"catalog.service":            "Service",
		"catalog.disabled":           "disabled",
		"catalog.managed":            "The catalog mode is managed by the administrator.",
		"user_interface.link":        "User interface",
		"login.password":             "Password",
		"login.submit":               "Sign in",
		"login.invalid_password":     "Invalid password",
		"login.rate_limit":           "Too many login attempts. Please try again later.",
		"login.error_empty":          "Login and password are required.",
		"login.error_invalid":        "Invalid login or password.",
		"login.error_ip":             "Your IP address does not match the user's authorized networks.",
		"login.not_implemented":      "Login with credentials is not yet implemented. Please use network auth for now.",
		"user.login":                 "Login",
		"user.password":              "Password",
		"user.logout":                "Logout",
		"admin.logout":               "Logout",
		"selection.heading":          "Service selection",
		"selection.category_hint":    "Selecting a whole category also includes services added to it later.",
		"selection.saved":            "Selection saved and BGP announcements updated.",
		"selection.save_failed":      "BGP announcements could not be updated.",
		"selection.locked":           "Selection is locked by the administrator.",
		"selection.selected":         "Selected:",
		"selection.category_one":     "category",
		"selection.category_few":     "categories",
		"selection.category_many":    "categories",
		"selection.service_one":      "service",
		"selection.service_few":      "services",
		"selection.service_many":     "services",
		"selection.in_categories":    "in them",
		"selection.standalone_one":   "standalone service",
		"selection.standalone_few":   "standalone services",
		"selection.standalone_many":  "standalone services",
		"selection.apply_hint":       "Changes take effect immediately after saving",
		"selection.save":             "Save routes",
		"selection.whole_category":   "all",
		"selection.empty":            "The catalog is empty.",
		"filters.heading":            "Route filtering",
		"filters.explanation":        `The "extend" mode combines global and user lists. The "replace" mode uses only user lists. An empty allow list permits all selected routes; deny entries are subtracted from broader prefixes.`,
		"filters.mode":               "Filter mode",
		"filters.mode_global":        "use global lists only",
		"filters.mode_extend":        "extend global lists with user lists",
		"filters.mode_override":      "replace global lists with user lists",
		"filters.allow":              "Allow CIDR, one per line",
		"filters.allow_placeholder":  "Empty = allow all",
		"filters.deny":               "Deny CIDR, one per line",
		"filters.save":               "Save filter",
		"filters.managed_override":   "User lists managed by the administrator are used.",
		"filters.managed_extend":     "Global lists are extended with user lists managed by the administrator.",
		"filters.managed_global":     "Global lists managed by the administrator are used.",
		"feeds.heading":              "Feeds",
		"feeds.name":                 "Name",
		"feeds.last_download":        "Last download",
		"feeds.last_sync":            "Last sync",
		"feeds.status":               "Status",
		"feeds.error":                "Error",
		"feeds.enabled":              "Enabled",
		"feeds.actions":              "Actions",
		"feeds.add":                  "Add feed",
		"feeds.sync_all":             "Sync All Feeds",
		"feeds.download_now":         "Download feeds now",
		"feeds.edit":                 "Edit Feed",
		"feeds.url":                  "URL",
		"feeds.data":                 "Adapter data (JSON)",
		"feeds.adapter":              "Adapter",
		"feeds.sync_interval":        "Sync interval (seconds)",
		"feeds.default_interval":     "Default",
		"feeds.delete_confirm":       "Delete this feed and its downloaded catalog entries?",
		"feeds.force_sync":           "Force sync",
		"adapters.heading":           "Feed adapters",
		"adapters.adapter":           "Adapter",
		"adapters.key":               "Key",
		"adapters.add":               "Add adapter",
		"adapters.source":            "JavaScript source",
		"adapters.allowed_hosts":     "Additional allowed HTTP hosts",
		"adapters.hint":              "Adapters run with a limited API. Saving validates JavaScript syntax; changes take effect on the next synchronization.",
		"adapters.test":              "Test",
		"adapters.test_feed":         "Test feed",
		"adapters.select_feed":       "Select a feed",
		"adapters.feed":              "Feed",
		"adapters.test_result":       "Adapter test result",
		"adapters.test_success":      "Adapter returned %d normalized CIDRs.",
		"adapters.preview_truncated": "Showing the first 100 CIDRs.",
		"adapters.preview_empty":     "The adapter returned no CIDRs.",
		"adapters.edit":              "Edit",
		"adapters.revision":          "Revision",
		"adapters.built_in":          "built in",
		"adapters.error":             "JavaScript error",
		"adapters.back_to_editor":    "Back to adapter",
		"adapters.reset":             "Reset to distribution version",
		"adapters.reset_confirm":     "Replace this adapter with the distribution version?",
		"title.adapter_test":         "Adapter test",
		"title.adapter_edit":         "Edit adapter",
		"title.communities":          "Communities",
		"communities.title":          "Communities",
		"communities.link":           "Communities",
		"selection.prefix_count":         "Unique prefixes in this category/service",
		"communities.group_community":  "Group community",
		"communities.service_community": "Service community",
		"communities.auto_generated":    "Auto-generated",
		"communities.revert":            "Revert to auto",
		"communities.apply":             "Apply Changes",
		"communities.cancel":            "Cancel",
		"communities.confirm":           "N communities will be updated. Continue?",
		"communities.saved":             "Communities saved.",
		"communities.reset_all":         "Reset all to auto",
		"communities.auto_generate":     "Auto-generate missing",
		"communities.no_changes":        "No changes",
		"communities.generate_confirm": "Generate community numbers for all categories and services that do not have one yet?",
		"communities.reset_confirm":    "This will reset ALL community numbers to auto-generated values. Any manual changes will be lost. Continue?",
		"communities.apply_edit_confirm": "Apply changes to this community number?",
		"communities.duplicate_error":  "This community number is already used. Please choose a different number.",
		"communities.changed_one":      "community number changed",
		"communities.changed_many":     "community numbers changed",
		"communities.reverted":         "reverted to auto",
		"common.add":                 "Add",
		"common.edit":                "Edit",
		"common.save":                "Save",
		"common.delete":              "Delete",
		"global_filters.heading":     "Global route filtering",
		"global_filters.explanation": "An empty allow list permits all selected routes. Deny subnets are subtracted from broader announcements. Default routes from feeds are always discarded.",
		"global_filters.save":        "Save global filter",
		"users.heading":              "Users",
		"users.cidr":                 "CIDR",
		"users.peer":                 "BGP peer",
		"users.asn":                  "ASN",
		"users.status":               "Status",
		"users.add":                  "Add user",
		"users.networks":             "User CIDRs, comma-separated",
		"users.peer_ip":              "BGP peer IP",
		"users.peer_asn":             "Peer ASN",
		"users.next_hop":             "Announcement next hop",
		"users.bgp_password":         "BGP MD5 password",
		"users.bgp_password_placeholder": "Leave empty to keep current password",
		"users.bgp_section":         "BGP",
		"users.dynamic_ip":          "Dynamic (0.0.0.0) — accept from any IP",
		"users.active_dial":         "Active dial",
		"users.access_section":      "Access",
		"users.web_auth":              "Web auth",
		"users.web_auth_network":      "Network (IP only)",
		"users.web_auth_login":        "Login (credentials)",
		"users.web_auth_both":         "Both (IP + credentials)",
		"users.web_auth_any":          "Any (IP or password)",
		"users.web_auth_hint":         "How the user is identified when accessing the selection page. Separate from BGP peer authentication.",
		"users.credentials":           "Credentials",
		"users.new_credential":        "New login",
		"users.allow_filter_editing": "allow the user to configure the filter mode and lists",
		"users.allow_mode_editing":   "allow the user to change the catalog mode",
		"user.settings":              "User settings",
		"user.password_set":          "Password is set; leave empty to keep it",
		"user.password_not_set":      "Not set",
		"user.clear_password":        "clear BGP MD5 password",
		"user.enabled":               "user is enabled",
		"user.lock_selection":        "prevent the user from changing the selection",
		"user.save":                  "Save settings",
		"user.delete":                "Delete user",
		"user.delete_confirm":        "Delete this user? This also deletes their service selection.",
		"bgp.state.ESTABLISHED":     "Established — BGP session is up",
		"bgp.state.IDLE":            "Idle — waiting to reconnect",
		"bgp.state.CONNECT":         "Connect — dialing the peer",
		"bgp.state.OPENSENT":        "OpenSent — OPEN message sent",
		"bgp.state.OPENCONFIRM":     "OpenConfirm — waiting for KEEPALIVE",
		"error.forbidden":            "forbidden",
		"error.selection_locked":     "selection is locked by the administrator",
		"error.filters_managed":      "route filters are managed by the administrator",
		"error.catalog_managed":      "catalog mode is managed by the administrator",
		"error.bad_request":          "bad request",
		"error.bad_user_id":          "bad user id",
		"error.bad_feed_id":          "bad feed id",
		"error.bad_mode_id":          "bad catalog mode id",
		"error.database_unavailable": "database unavailable",
		"error.internal":             "internal server error",
		"nav.dashboard":              "Dashboard",
		"nav.users":                  "Users",
		"nav.feeds":                  "Feeds",
		"nav.communities":            "Communities",
		"nav.adapters":               "Adapters",
		"nav.settings":               "Settings",
		"nav.user_page":              "User page",
		"nav.modes":                  "Catalog Modes",
		"modes.heading":              "Catalog Modes",
		"catalog.modes_saved":        "Catalog modes saved.",
		"catalog.mode_add":           "Add catalog mode",
		"catalog.mode_name":          "Mode name",
		"catalog.mode_delete_confirm": "Delete this catalog mode? This will also remove it from all feeds.",
		"stats.prefixes":             "Prefixes from feeds",
		"stats.users":                "Users",
		"stats.bgp_peers":            "BGP peers",
		"stats.feeds":                "Feeds enabled",
		"stats.categories":           "Categories",
		"stats.services":             "Services",

		// Hint texts
		"hints.feed_name":            "Short descriptive name for this feed",
		"hints.feed_url":             "URL to fetch the prefix list from (HTTP or HTTPS)",
		"hints.feed_sync_interval":   "Seconds between automatic syncs (0 = manual only)",
		"hints.feed_data":            "JSON config string passed to the adapter script",
		"hints.user_name":            "Display name for this BGP peer",
		"hints.user_networks":        "Comma-separated CIDR blocks identifying this user on the web",
		"hints.user_peer_ip":         "BGP neighbor IP address",
		"hints.user_peer_asn":        "Autonomous System Number of the remote peer",
		"hints.user_catalog_mode":    "Which catalog mode this user sees and selects from",
		"hints.mode_name":            "Human-readable name for this catalog mode",
		"hints.user_next_hop":        "Override the BGP next-hop address (optional, leave empty for auto)",
		"hints.user_dynamic_ip":      "Accept connections from any IP address (the peer must authenticate via password+ASN)",
		"hint.dynamic_peers_disabled": "Dynamic peers disabled. Set WDBGP_ALLOW_DYNAMIC_PEERS=true to use.",
		"hint.dynamic_no_password":    "TCP MD5 requires known peer IP. No authentication for wildcard addresses.",
		"hint.same_ip_password":       "Kernel supports one MD5 key per IP. All peers at this address must share the same password.",
		"hints.active_dial":           "When enabled, the speaker initiates BGP connections to this peer. Disable for passive-only (listen-only) mode.",
		"hints.active_dial_system_disabled": "Active dial is disabled system-wide (WDBGP_ACTIVE_DIAL=false).",

		// Settings page
		"settings.section_general":     "General",
		"settings.section_rate_limit":  "Rate Limiting",
		"settings.section_logging":     "Logging",
		"settings.section_sync":        "Feed Synchronization",
		"settings.section_js":          "JavaScript Runtime",
		"settings.section_bgp":         "BGP (restart required)",
		"settings.section_network":     "Network (restart required)",
		"settings.section_filters":     "Global route filtering",

		"settings.default_language":    "Default language",
		"settings.session_max_age":     "Session max age",
		"settings.admin_cookie_secure": "Cookie Secure flag",
		"settings.trust_proxy_headers": "Trust proxy headers",
		"settings.security_headers":    "Security headers",
		"settings.default_web_auth":    "Default web auth mode",
		"settings.status_allowed": "Status allowed CIDRs",
		"settings.status_token": "Status API token",
		"settings.rate_limit_login":    "Login rate limit",
		"settings.rate_limit_admin":    "Admin rate limit",
		"settings.log_level":           "Log level",
		"settings.log_format":          "Log format",
		"settings.sync_interval":       "Sync interval",
		"settings.js_timeout":          "JS execution timeout",
		"settings.js_max_source":       "JS max source bytes",
		"settings.js_max_response":     "JS max response bytes",
		"settings.js_max_total":        "JS max total bytes",
		"settings.js_max_entries":      "JS max entries",
		"settings.js_max_requests":     "JS max HTTP requests",
		"settings.js_max_call_stack":   "JS max call stack",
		"settings.bgp_port":            "BGP listen port",
		"settings.local_asn":           "Local ASN",
		"settings.router_id":           "Router ID",
		"settings.local_address_v4":    "Local IPv4 address",
		"settings.local_address_v6":    "Local IPv6 address",
		"settings.host":                "HTTP host",
		"settings.port":                "HTTP port",
		"settings.allow_dynamic_peers": "Allow dynamic peers",
		"settings.auto_restore_enabled": "Auto-restore from backup",

		"settings.default_language_hint": "Default interface language for new visitors. Environment variable: WDBGP_DEFAULT_LANGUAGE.",
		"settings.session_max_age_hint": "Maximum session lifetime in seconds (default 28800 = 8 hours). Environment variable: WDBGP_SESSION_MAX_AGE.",
		"settings.admin_cookie_secure_hint": "Sets the Secure flag on admin session cookies. auto — heuristically secure behind a proxy, true — always, false — never (needed for HTTP dev). Environment variable: WDBGP_ADMIN_COOKIE_SECURE.",
		"settings.trust_proxy_headers_hint": "Whether to trust X-Forwarded-* headers from reverse proxies for client IP detection. Environment variable: WDBGP_TRUST_PROXY_HEADERS.",
		"settings.security_headers_hint": "Add HSTS, CSP, X-Frame-Options and other security headers to HTTP responses. Environment variable: WDBGP_SECURITY_HEADERS.",
		"settings.default_web_auth_hint": "Default web authentication mode for new users: network (IP only), login (credentials), both (IP + credentials), any (IP or password). Environment variable: WDBGP_DEFAULT_WEB_AUTH.",
		"settings.status_allowed_hint": "Comma-separated CIDR list for /status endpoint access. Empty = no IP access. Environment variable: WDBGP_STATUS_ALLOWED.",
		"settings.status_token_hint": "Bearer token for /status endpoint access via Authorization header. Empty = no token access. Environment variable: WDBGP_STATUS_TOKEN.",
		"settings.rate_limit_login_hint": "Maximum login attempts per minute per IP. Environment variable: WDBGP_RATE_LIMIT_LOGIN.",
		"settings.rate_limit_admin_hint": "Maximum admin API requests per minute per IP. Environment variable: WDBGP_RATE_LIMIT_ADMIN.",
		"settings.log_level_hint": "Minimum log severity level: DEBUG, INFO, WARN, ERROR, FATAL, PANIC. Environment variable: WDBGP_LOG_LEVEL.",
		"settings.log_format_hint": "Log output format: text (human-readable) or json (structured). Environment variable: WDBGP_LOG_FORMAT.",
		"settings.sync_interval_hint": "Interval in seconds between automatic feed synchronizations. Environment variable: WDBGP_SYNC_INTERVAL.",
		"settings.js_timeout_hint": "Maximum time in seconds a feed adapter script is allowed to run. Environment variable: WDBGP_JS_TIMEOUT.",
		"settings.js_max_source_hint": "Maximum size in bytes of a feed adapter JavaScript source. Environment variable: WDBGP_JS_MAX_SOURCE.",
		"settings.js_max_response_hint": "Maximum size in bytes of an HTTP response body the adapter runtime can hold. Environment variable: WDBGP_JS_MAX_RESPONSE.",
		"settings.js_max_total_hint": "Maximum total bytes of all HTTP response bodies combined per adapter execution. Environment variable: WDBGP_JS_MAX_TOTAL.",
		"settings.js_max_entries_hint": "Maximum number of CIDR entries a single adapter script may produce. Environment variable: WDBGP_JS_MAX_ENTRIES.",
		"settings.js_max_requests_hint": "Maximum number of HTTP requests an adapter script is allowed to make. Environment variable: WDBGP_JS_MAX_REQUESTS.",
		"settings.js_max_call_stack_hint": "Maximum call stack depth for adapter JavaScript execution. Environment variable: WDBGP_JS_MAX_CALL_STACK.",
		"settings.bgp_port_hint": "TCP port for BGP peer connections (default 179). Environment variable: WDBGP_BGP_PORT.",
		"settings.local_asn_hint": "Autonomous System Number advertised to BGP peers. Environment variable: WDBGP_LOCAL_ASN.",
		"settings.router_id_hint": "BGP Router ID (IPv4 address format). Environment variable: WDBGP_ROUTER_ID.",
		"settings.local_address_v4_hint": "IPv4 address used for BGP sessions. Environment variable: WDBGP_BGP_LOCAL_ADDRESS.",
		"settings.local_address_v6_hint": "IPv6 address used for BGP sessions. Empty = no IPv6 BGP. Environment variable: WDBGP_BGP_LOCAL_ADDRESS_V6.",
		"settings.host_hint": "IP address or hostname the HTTP server binds to. Environment variable: WDBGP_HOST.",
		"settings.port_hint": "TCP port the HTTP server listens on. Environment variable: WDBGP_PORT.",
		"settings.allow_dynamic_peers_hint": "Controlled by WDBGP_ALLOW_DYNAMIC_PEERS. Cannot be changed via UI.",
		"settings.auto_restore_enabled_hint": "Automatically restore database from a matching backup when the DB schema is newer than the server. Controlled by WDBGP_AUTO_RESTORE_ENABLED. Cannot be changed via UI.",

		"settings.default":            "Default",
		"settings.saved":              "Settings saved.",
		"settings.env_override":       "ENV override",
		"settings.env_override_hint":  "This setting is controlled by an environment variable and cannot be changed here.",
		"settings.auto":               "auto",
		"settings.true":               "true",
		"settings.false":              "false",
		"settings.help":               "Help",
		"settings.requires_restart":   "requires restart",

		"settings.session_max_age_placeholder": "Default: 28800",
		"settings.rate_limit_login_placeholder": "Default: 5",
		"settings.rate_limit_admin_placeholder": "Default: 30",
		"settings.sync_interval_placeholder": "Default: 3600",
		"settings.js_timeout_placeholder": "Default: 120",
		"settings.js_max_source_placeholder": "Default: 1048576",
		"settings.js_max_response_placeholder": "Default: 16777216",
		"settings.js_max_total_placeholder": "Default: 67108864",
		"settings.js_max_entries_placeholder": "Default: 1000000",
		"settings.js_max_requests_placeholder": "Default: 200",
		"settings.js_max_call_stack_placeholder": "Default: 1000",
		"settings.status_allowed_placeholder": "e.g. 10.0.0.0/8,172.16.0.0/12",
		"settings.status_token_placeholder": "secret-token",

		"settings.adapter_backup_dir": "Adapter backup directory",
		"settings.adapter_backup_dir_hint": "Directory for adapter source backups on edit/delete. Empty = disabled. Default: <db_dir>/backup/adapters. Environment variable: WDBGP_ADAPTER_BACKUP_DIR.",
		"settings.adapter_backup_dir_placeholder": "e.g. /data/backup/adapters",
		"settings.adapter_backup_max": "Max backup copies per adapter",
		"settings.adapter_backup_max_hint": "Maximum backup files kept per adapter. Oldest are deleted first. 0 = unlimited. Environment variable: WDBGP_ADAPTER_BACKUP_MAX.",
		"settings.adapter_backup_max_placeholder": "Default: 10",

		"error.db_too_new":     "Database schema version %d is newer than server version %d.",
		"error.db_too_new_hint": "Set WDBGP_AUTO_RESTORE_ENABLED=true to auto-restore from a backup.",
		"error.db_no_backup":    "Auto-restore enabled but no matching backup found.",
		"title.db_mismatch":     "Database Version Mismatch",
}
