package web

var ruTranslations = map[string]string{ //nolint:gosec // i18n strings, not credentials
	"language.label":                 "Язык",
	"language.english":               "Английский",
	"language.russian":               "Русский",
	"title.access_denied":            "Нет доступа",
	"title.selection":                "Выбор маршрутов",
	"title.login":                    "Вход",
	"title.admin":                    "Админка",
	"title.user":                     "Пользователь %s",
	"access_denied.heading":          "Нет доступа",
	"admin.heading":                  "Админка",
	"admin.link":                     "Админка",
	"bgp.established":                "BGP-сессия установлена",
	"bgp.unknown":                    "Состояние BGP неизвестно",
	"debug.heading":                  "Диагностика CIDR",
	"debug.description":              "Показывает, какие сервисы включённых фидов и выборы пользователей покрывают IP-адрес или подсеть. Покрытие пользователей отображается до и после применения эффективных allow/deny-фильтров маршрутов.",
	"debug.input":                    "IP-адрес или CIDR",
	"debug.submit":                   "Проверить",
	"debug.results":                  "Диагностика покрытия",
	"debug.full_services":            "Сервисы с полным покрытием",
	"debug.partial_services":         "Сервисы с частичным покрытием",
	"debug.combined":                 "Совокупное покрытие сервисами",
	"debug.users":                    "Включённые пользователи с подходящим выбором",
	"debug.no_matches":               "Подходящие включённые сервисы и пользователи не найдены.",
	"debug.no_items":                 "Нет",
	"debug.coverage":                 "покрытие",
	"debug.before_filters":           "до фильтров",
	"debug.after_filters":            "после фильтров",
	"debug.close":                    "Закрыть",
	"debug.request_failed":           "Не удалось выполнить анализ CIDR.",
	"catalog.mode":                   "Режим каталога",
	"catalog.modes":                  "Режимы каталогов",
	"catalog.modes_hint":             "Только включённые режимы доступны пользователям и участвуют в анонсах и диагностике.",
	"catalog.key":                    "Ключ",
	"catalog.category":               "Категория",
	"catalog.service":                "Сервис",
	"catalog.disabled":               "отключён",
	"catalog.managed":                "Режим каталога управляется администратором.",
	"user_interface.link":            "Пользовательский интерфейс",
	"login.password":                 "Пароль",
	"login.submit":                   "Войти",
	"login.invalid_password":         "Неверный пароль",
	"login.rate_limit":               "Слишком много попыток входа. Попробуйте позже.",
	"login.error_empty":              "Логин и пароль обязательны.",
	"login.error_invalid":            "Неверный логин или пароль.",
	"login.error_ip":                 "Ваш IP-адрес не совпадает с разрешёнными сетями пользователя.",
	"login.not_implemented":          "Вход по учетным данным еще не реализован. Пожалуйста, используйте сетевую аутентификацию.",
	"user.login":                     "Логин",
	"user.password":                  "Пароль",
	"user.logout":                    "Выйти",
	"admin.logout":                   "Выйти",
	"selection.heading":              "Выбор сервисов",
	"selection.category_hint":        "Категория целиком включает также сервисы, которые появятся в ней позже.",
	"selection.saved":                "Выбор сохранён, BGP-анонсы обновлены.",
	"selection.save_failed":          "Не удалось обновить BGP-анонсы.",
	"selection.locked":               "Выбор заблокирован администратором.",
	"selection.selected":             "Выбрано:",
	"selection.category_one":         "категория",
	"selection.category_few":         "категории",
	"selection.category_many":        "категорий",
	"selection.service_one":          "сервис",
	"selection.service_few":          "сервиса",
	"selection.service_many":         "сервисов",
	"selection.in_categories":        "в них",
	"selection.standalone_one":       "отдельный сервис",
	"selection.standalone_few":       "отдельных сервиса",
	"selection.standalone_many":      "отдельных сервисов",
	"selection.apply_hint":           "Изменения применяются сразу после сохранения",
	"selection.save":                 "Сохранить маршруты",
	"selection.whole_category":       "целиком",
	"selection.empty":                "Каталог пока пуст.",
	"filters.heading":                "Фильтрация маршрутов",
	"filters.explanation":            `Режим "дополнить" применяет глобальные и пользовательские списки вместе. Режим "заменить" использует только пользовательские списки. Пустой allow разрешает все выбранные маршруты; deny вырезается из широких префиксов.`,
	"filters.mode":                   "Режим фильтрации",
	"filters.mode_global":            "использовать только глобальные списки",
	"filters.mode_extend":            "дополнить глобальные списки пользовательскими",
	"filters.mode_override":          "заменить глобальные списки пользовательскими",
	"filters.allow":                  "Allow CIDR, по одному на строку",
	"filters.allow_placeholder":      "Пусто = разрешить всё",
	"filters.deny":                   "Deny CIDR, по одному на строку",
	"filters.save":                   "Сохранить фильтр",
	"filters.managed_override":       "Используются пользовательские списки, управляемые администратором.",
	"filters.managed_extend":         "Глобальные списки дополнены пользовательскими списками администратора.",
	"filters.managed_global":         "Используются глобальные списки администратора.",
	"feeds.heading":                  "Фиды",
	"feeds.name":                     "Имя",
	"feeds.last_download":            "Последняя загрузка",
	"feeds.last_sync":                "Последняя синхронизация",
	"feeds.status":                   "Состояние",
	"feeds.error":                    "Ошибка",
	"feeds.enabled":                  "Включён",
	"feeds.actions":                  "Действия",
	"feeds.add":                      "Добавить фид",
	"feeds.sync_all":                 "Синхронизировать все фиды",
	"feeds.download_now":             "Скачать фиды сейчас",
	"feeds.edit":                     "Редактировать фид",
	"feeds.url":                      "URL",
	"feeds.data":                     "Данные адаптера (JSON)",
	"feeds.adapter":                  "Адаптер",
	"feeds.sync_interval":            "Интервал синхронизации (секунд)",
	"feeds.default_interval":         "По умолчанию",
	"feeds.delete_confirm":           "Удалить фид и загруженные из него записи каталога?",
	"feeds.force_sync":               "Принудительная синхронизация",
	"adapters.heading":               "Адаптеры фидов",
	"adapters.adapter":               "Адаптер",
	"adapters.key":                   "Ключ",
	"adapters.add":                   "Добавить адаптер",
	"adapters.source":                "Исходный код JavaScript",
	"adapters.allowed_hosts":         "Дополнительные разрешённые HTTP-хосты",
	"adapters.hint":                  "Адаптеры работают с ограниченным API. При сохранении проверяется синтаксис JavaScript; изменения применяются при следующей синхронизации.",
	"adapters.test":                  "Тест",
	"adapters.test_feed":             "Фид для теста",
	"adapters.select_feed":           "Выберите фид",
	"adapters.feed":                  "Фид",
	"adapters.test_result":           "Результат теста адаптера",
	"adapters.test_success":          "Адаптер вернул %d нормализованных CIDR.",
	"adapters.preview_truncated":     "Показаны первые 100 CIDR.",
	"adapters.preview_empty":         "Адаптер не вернул CIDR.",
	"adapters.edit":                  "Редактировать",
	"adapters.revision":              "Ревизия",
	"adapters.built_in":              "встроенный",
	"adapters.error":                 "Ошибка JavaScript",
	"adapters.back_to_editor":        "Вернуться к адаптеру",
	"adapters.reset":                 "Сбросить к версии из дистрибутива",
	"adapters.reset_confirm":         "Заменить адаптер версией из дистрибутива?",
	"title.adapter_test":             "Тест адаптера",
	"title.adapter_edit":             "Редактирование адаптера",
	"title.communities":              "Комьюнити",
	"communities.title":              "Комьюнити",
	"communities.link":               "Комьюнити",
	"selection.prefix_count":         "Уникальных префиксов в этой категории/сервисе",
	"communities.group_community":    "Комьюнити группы",
	"communities.service_community":  "Комьюнити сервиса",
	"communities.auto_generated":     "Авто-сгенерировано",
	"communities.revert":             "Вернуть авто",
	"communities.apply":              "Применить изменения",
	"communities.cancel":             "Отмена",
	"communities.confirm":            "Будет обновлено N комьюнити. Продолжить?",
	"communities.saved":              "Комьюнити сохранены.",
	"communities.reset_all":          "Сбросить все на авто",
	"communities.auto_generate":      "Авто-генерация отсутствующих",
	"communities.no_changes":         "Нет изменений",
	"communities.generate_confirm":   "Сгенерировать номера комьюнити для всех категорий и сервисов, у которых их нет?",
	"communities.reset_confirm":      "Это сбросит ВСЕ номера комьюнити на авто-сгенерированные значения. Ручные изменения будут потеряны. Продолжить?",
	"communities.apply_edit_confirm": "Применить изменения для этого номера комьюнити?",
	"communities.duplicate_error":    "Этот номер комьюнити уже используется. Выберите другой номер.",
	"communities.changed_one":        "номер комьюнити изменён",
	"communities.changed_many":       "номеров комьюнити изменено",
	"communities.reverted":           "возвращено к авто",
	"common.add":                     "Добавить",
	"common.edit":                    "Редактировать",
	"common.save":                    "Сохранить",
	"common.delete":                  "Удалить",
	"global_filters.heading":         "Глобальная фильтрация маршрутов",
	"global_filters.explanation":     "Пустой allow разрешает все выбранные маршруты. Deny-подсети физически вырезаются из более широких анонсов. Default routes из фидов всегда отбрасываются.",
	"global_filters.save":            "Сохранить глобальный фильтр",
	"users.heading":                  "Пользователи",
	"users.cidr":                     "CIDR",
	"users.peer":                     "BGP peer",
	"users.asn":                      "ASN",
	"users.status":                   "Состояние",
	"users.add":                      "Добавить пользователя",
	"users.networks":                 "Пользовательские CIDR, через запятую",
	"users.peer_ip":                  "IP BGP peer",
	"users.peer_asn":                 "ASN peer",
	"users.next_hop":                 "Next hop для анонсов",
	"users.bgp_password":             "BGP MD5 пароль",
	"users.bgp_password_placeholder": "Оставьте пустым чтобы сохранить текущий пароль",
	"users.bgp_section":              "BGP",
	"users.dynamic_ip":               "Динамический (0.0.0.0) — принимать с любого IP",
	"users.active_dial":              "Активный дозвон",
	"users.access_section":           "Доступ",
	"users.web_auth":                 "Веб-аутентификация",
	"users.web_auth_network":         "Сеть (только IP)",
	"users.web_auth_login":           "Логин (учетные данные)",
	"users.web_auth_both":            "Оба (IP + учетные данные)",
	"users.web_auth_any":             "Любой (IP или пароль)",
	"users.web_auth_hint":            "Как пользователь идентифицируется при доступе к странице выбора. Отдельно от аутентификации BGP-пира.",
	"users.credentials":              "Учётные данные",
	"users.new_credential":           "Новый логин",
	"users.credential_add":           "Добавить",
	"users.credential_create":        "Создать",
	"users.credential_login":         "Логин",
	"users.credential_password":      "Пароль",
	"users.credential_delete":        "Удалить",
	"users.credential_reset_pw":      "Сменить пароль",
	"users.credential_login_hint":    "Имя пользователя для веб-аутентификации",
	"users.credential_password_hint": "Пароль для веб-аутентификации",
	"users.credentials_not_needed":   "Для этого метода аутентификации учётные данные не нужны",
	"users.allow_filter_editing":     "разрешить пользователю настраивать режим и списки фильтрации",
	"users.allow_mode_editing":       "разрешить пользователю менять режим каталога",
	"user.settings":                  "Параметры пользователя",
	"user.password_set":              "Пароль задан; пустое поле не изменит его",
	"user.password_not_set":          "Не задан",
	"user.clear_password":            "очистить BGP MD5 пароль",
	"user.enabled":                   "пользователь включён",
	"user.lock_selection":            "запретить пользователю менять выбор",
	"user.save":                      "Сохранить параметры",
	"user.delete":                    "Удалить пользователя",
	"user.delete_confirm":            "Удалить пользователя? Это также удалит его выбор сервисов.",
	"bgp.state.ESTABLISHED":          "Established — BGP-сессия активна",
	"bgp.state.IDLE":                 "Idle — ожидание переподключения",
	"bgp.state.CONNECT":              "Connect — подключение к пиру",
	"bgp.state.OPENSENT":             "OpenSent — отправлен OPEN",
	"bgp.state.OPENCONFIRM":          "OpenConfirm — ожидание KEEPALIVE",
	"error.forbidden":                "нет доступа",
	"error.selection_locked":         "выбор заблокирован администратором",
	"error.filters_managed":          "фильтрация маршрутов управляется администратором",
	"error.catalog_managed":          "режим каталога управляется администратором",
	"error.bad_request":              "неверный запрос",
	"error.bad_user_id":              "неверный идентификатор пользователя",
	"error.bad_feed_id":              "неверный идентификатор фида",
	"error.bad_mode_id":              "неверный идентификатор режима каталога",
	"error.database_unavailable":     "база данных недоступна",
	"error.internal":                 "внутренняя ошибка сервера",
	"nav.dashboard":                  "Дашборд",
	"nav.users":                      "Пользователи",
	"nav.feeds":                      "Фиды",
	"nav.communities":                "Комьюнити",
	"nav.adapters":                   "Адаптеры",
	"nav.settings":                   "Настройки",
	"nav.user_page":                  "Страница пользователя",
	"nav.modes":                      "Режимы каталогов",
	"modes.heading":                  "Режимы каталогов",
	"catalog.modes_saved":            "Режимы каталогов сохранены.",
	"catalog.mode_add":               "Добавить режим каталога",
	"catalog.mode_name":              "Название режима",
	"catalog.mode_delete_confirm":    "Удалить этот режим каталога? Он также будет удалён из всех фидов.",
	"stats.prefixes":                 "Префиксов от фидов",
	"stats.users":                    "Пользователей",
	"stats.bgp_peers":                "BGP-пиров",
	"stats.feeds":                    "Фидов активно",
	"stats.categories":               "Категорий",
	"stats.services":                 "Сервисов",

	// Hint texts
	"hints.feed_name":                   "Краткое название фида",
	"hints.feed_url":                    "URL для получения списка префиксов (HTTP или HTTPS)",
	"hints.feed_sync_interval":          "Интервал автосинхронизации в секундах (0 = только вручную)",
	"hints.feed_data":                   "JSON-конфиг, передаваемый скрипту адаптера",
	"hints.user_name":                   "Отображаемое имя BGP-пира",
	"hints.user_networks":               "CIDR-блоки пользователя через запятую",
	"hints.user_peer_ip":                "IP-адрес BGP-соседа",
	"hints.user_peer_asn":               "Номер автономной системы удалённого пира",
	"hints.user_catalog_mode":           "Режим каталога, который видит пользователь",
	"hints.mode_name":                   "Человекочитаемое имя режима каталога",
	"hints.user_next_hop":               "Переопределить BGP next-hop адрес (опционально, пусто = auto)",
	"hints.user_dynamic_ip":             "Принимать подключения с любого IP-адреса (пир должен подтвердить пароль+ASN)",
	"hint.dynamic_peers_disabled":       "Динамические пиры отключены. Установите WDBGP_ALLOW_DYNAMIC_PEERS=true.",
	"hint.dynamic_no_password":          "TCP MD5 требует известный IP пира. Аутентификация для wildcard-адресов невозможна.",
	"hint.same_ip_password":             "Ядро поддерживает один MD5 ключ на IP. Все пиры на этом адресе должны использовать одинаковый пароль.",
	"hints.active_dial":                 "При включении спикер сам устанавливает BGP-соединение с этим пиром. Выключите для пассивного режима (только приём входящих).",
	"hints.active_dial_system_disabled": "Активный дозвон отключен глобально (WDBGP_ACTIVE_DIAL=false).",

	// Settings page
	"settings.section_general":    "Общие",
	"settings.section_rate_limit": "Ограничения",
	"settings.section_logging":    "Логирование",
	"settings.section_sync":       "Синхронизация фидов",
	"settings.section_js":         "JavaScript Runtime",
	"settings.section_bgp":        "BGP (требуется перезапуск)",
	"settings.section_network":    "Сеть (требуется перезапуск)",
	"settings.section_filters":    "Глобальная фильтрация маршрутов",

	"settings.default_language":     "Язык по умолчанию",
	"settings.session_max_age":      "Время жизни сессии",
	"settings.admin_cookie_secure":  "Флаг Secure cookie",
	"settings.trust_proxy_headers":  "Доверять заголовкам прокси",
	"settings.security_headers":     "Заголовки безопасности",
	"settings.default_web_auth":     "Веб-аутентификация по умолчанию",
	"settings.status_allowed":       "CIDR для статуса",
	"settings.status_token":         "Токен статуса",
	"settings.rate_limit_login":     "Лимит входа",
	"settings.rate_limit_admin":     "Лимит админки",
	"settings.log_level":            "Уровень логирования",
	"settings.log_format":           "Формат логов",
	"settings.sync_interval":        "Интервал синхронизации",
	"settings.js_timeout":           "Таймаут JS",
	"settings.js_max_source":        "Макс. размер исходника JS",
	"settings.js_max_response":      "Макс. размер ответа JS",
	"settings.js_max_total":         "Макс. общий размер JS",
	"settings.js_max_entries":       "Макс. записей JS",
	"settings.js_max_requests":      "Макс. запросов JS",
	"settings.js_max_call_stack":    "Макс. стек вызовов JS",
	"settings.bgp_port":             "Порт BGP",
	"settings.local_asn":            "Локальный ASN",
	"settings.router_id":            "Router ID",
	"settings.local_address_v4":     "Локальный IPv4 адрес",
	"settings.local_address_v6":     "Локальный IPv6 адрес",
	"settings.host":                 "HTTP хост",
	"settings.port":                 "HTTP порт",
	"settings.allow_dynamic_peers":  "Разрешить динамические пиры",
	"settings.auto_restore_enabled": "Автовосстановление из бэкапа",

	"settings.default_language_hint":     "Язык интерфейса по умолчанию для новых посетителей. Переменная окружения: WDBGP_DEFAULT_LANGUAGE.",
	"settings.session_max_age_hint":      "Максимальное время жизни сессии в секундах (по умолчанию 28800 = 8 часов). Переменная окружения: WDBGP_SESSION_MAX_AGE.",
	"settings.admin_cookie_secure_hint":  "Устанавливает флаг Secure для административных сессионных cookie. auto — эвристически безопасно за прокси, true — всегда, false — никогда (нужно для локальной HTTP-разработки). Переменная окружения: WDBGP_ADMIN_COOKIE_SECURE.",
	"settings.trust_proxy_headers_hint":  "Доверять ли заголовкам X-Forwarded-* от обратного прокси для определения IP клиента. Переменная окружения: WDBGP_TRUST_PROXY_HEADERS.",
	"settings.security_headers_hint":     "Добавлять HSTS, CSP, X-Frame-Options и другие заголовки безопасности в HTTP-ответы. Переменная окружения: WDBGP_SECURITY_HEADERS.",
	"settings.default_web_auth_hint":     "Режим веб-аутентификации по умолчанию для новых пользователей: network (только IP), login (учетные данные), both (IP + учетные данные), any (IP или пароль). Переменная окружения: WDBGP_DEFAULT_WEB_AUTH.",
	"settings.status_allowed_hint":       "Список CIDR через запятую для доступа к /status. Пусто = доступ по IP запрещён. Переменная окружения: WDBGP_STATUS_ALLOWED.",
	"settings.status_token_hint":         "Bearer-токен для доступа к /status через заголовок Authorization. Пусто = доступ по токену запрещён. Переменная окружения: WDBGP_STATUS_TOKEN.",
	"settings.rate_limit_login_hint":     "Максимальное количество попыток входа в минуту с одного IP. Переменная окружения: WDBGP_RATE_LIMIT_LOGIN.",
	"settings.rate_limit_admin_hint":     "Максимальное количество запросов к админке в минуту с одного IP. Переменная окружения: WDBGP_RATE_LIMIT_ADMIN.",
	"settings.log_level_hint":            "Минимальный уровень серьёзности логов: DEBUG, INFO, WARN, ERROR, FATAL, PANIC. Переменная окружения: WDBGP_LOG_LEVEL.",
	"settings.log_format_hint":           "Формат вывода логов: text (читаемый) или json (структурированный). Переменная окружения: WDBGP_LOG_FORMAT.",
	"settings.sync_interval_hint":        "Интервал в секундах между автоматическими синхронизациями фидов. Переменная окружения: WDBGP_SYNC_INTERVAL.",
	"settings.js_timeout_hint":           "Максимальное время в секундах, отведённое на выполнение скрипта адаптера. Переменная окружения: WDBGP_JS_TIMEOUT.",
	"settings.js_max_source_hint":        "Максимальный размер исходного кода JavaScript адаптера в байтах. Переменная окружения: WDBGP_JS_MAX_SOURCE.",
	"settings.js_max_response_hint":      "Максимальный размер тела HTTP-ответа, которое может удерживать среда выполнения адаптера. Переменная окружения: WDBGP_JS_MAX_RESPONSE.",
	"settings.js_max_total_hint":         "Максимальный суммарный размер всех тел HTTP-ответов за одно выполнение адаптера. Переменная окружения: WDBGP_JS_MAX_TOTAL.",
	"settings.js_max_entries_hint":       "Максимальное количество CIDR-записей, которое может создать один скрипт адаптера. Переменная окружения: WDBGP_JS_MAX_ENTRIES.",
	"settings.js_max_requests_hint":      "Максимальное количество HTTP-запросов, разрешённых скрипту адаптера. Переменная окружения: WDBGP_JS_MAX_REQUESTS.",
	"settings.js_max_call_stack_hint":    "Максимальная глубина стека вызовов JavaScript адаптера. Переменная окружения: WDBGP_JS_MAX_CALL_STACK.",
	"settings.bgp_port_hint":             "TCP-порт для BGP-подключений пиров (по умолчанию 179). Переменная окружения: WDBGP_BGP_PORT.",
	"settings.local_asn_hint":            "Номер автономной системы, анонсируемый BGP-пирам. Переменная окружения: WDBGP_LOCAL_ASN.",
	"settings.router_id_hint":            "BGP Router ID (формат IPv4 адреса). Переменная окружения: WDBGP_ROUTER_ID.",
	"settings.local_address_v4_hint":     "IPv4-адрес, используемый для BGP-сессий. Переменная окружения: WDBGP_BGP_LOCAL_ADDRESS.",
	"settings.local_address_v6_hint":     "IPv6-адрес, используемый для BGP-сессий. Пусто = нет IPv6 BGP. Переменная окружения: WDBGP_BGP_LOCAL_ADDRESS_V6.",
	"settings.host_hint":                 "IP-адрес или имя хоста, к которому привязывается HTTP-сервер. Переменная окружения: WDBGP_HOST.",
	"settings.port_hint":                 "TCP-порт, на котором слушает HTTP-сервер. Переменная окружения: WDBGP_PORT.",
	"settings.allow_dynamic_peers_hint":  "Управляется через WDBGP_ALLOW_DYNAMIC_PEERS. Нельзя изменить через интерфейс.",
	"settings.auto_restore_enabled_hint": "Автоматически восстанавливать базу данных из подходящего бэкапа, если схема БД новее сервера. Управляется через WDBGP_AUTO_RESTORE_ENABLED. Нельзя изменить через интерфейс.",

	"settings.default":           "По умолчанию",
	"settings.saved":             "Настройки сохранены.",
	"settings.env_override":      "ENV",
	"settings.env_override_hint": "Эта настройка задана переменной окружения и не может быть изменена здесь.",
	"settings.auto":              "авто",
	"settings.true":              "да",
	"settings.false":             "нет",
	"settings.help":              "Справка",
	"settings.requires_restart":  "требуется перезапуск",

	"settings.session_max_age_placeholder":   "По умолчанию: 28800",
	"settings.rate_limit_login_placeholder":  "По умолчанию: 5",
	"settings.rate_limit_admin_placeholder":  "По умолчанию: 30",
	"settings.sync_interval_placeholder":     "По умолчанию: 3600",
	"settings.js_timeout_placeholder":        "По умолчанию: 120",
	"settings.js_max_source_placeholder":     "По умолчанию: 1048576",
	"settings.js_max_response_placeholder":   "По умолчанию: 16777216",
	"settings.js_max_total_placeholder":      "По умолчанию: 67108864",
	"settings.js_max_entries_placeholder":    "По умолчанию: 1000000",
	"settings.js_max_requests_placeholder":   "По умолчанию: 200",
	"settings.js_max_call_stack_placeholder": "По умолчанию: 1000",
	"settings.status_allowed_placeholder":    "например 10.0.0.0/8,172.16.0.0/12",
	"settings.status_token_placeholder":      "секретный-токен",

	"settings.adapter_backup_dir":             "Папка бэкапов адаптеров",
	"settings.adapter_backup_dir_hint":        "Директория для бэкапов исходников адаптеров при редактировании/удалении. Пусто = отключено. По умолчанию: <db_dir>/backup/adapters. Переменная окружения: WDBGP_ADAPTER_BACKUP_DIR.",
	"settings.adapter_backup_dir_placeholder": "например /data/backup/adapters",
	"settings.adapter_backup_max":             "Макс. копий на адаптер",
	"settings.adapter_backup_max_hint":        "Максимальное количество хранимых бэкапов для одного адаптера. Старые удаляются первыми. 0 = без ограничений. Переменная окружения: WDBGP_ADAPTER_BACKUP_MAX.",
	"settings.adapter_backup_max_placeholder": "По умолчанию: 10",

	"error.db_too_new":      "Версия схемы базы данных %d новее, чем версия сервера %d.",
	"error.db_too_new_hint": "Установите WDBGP_AUTO_RESTORE_ENABLED=true для автовосстановления из бэкапа.",
	"error.db_no_backup":    "Автовосстановление включено, но подходящий бэкап не найден.",
	"title.db_mismatch":     "Несоответствие версии базы данных",
}
