//nolint:errcheck // test file, errors in cleanup intentionally ignored
package store

import (
	"database/sql"
	"path/filepath"
	"testing"

	_ "modernc.org/sqlite"
)

func TestMigrationDeduplicatesFeedsWithoutLosingCatalog(t *testing.T) {
	path := filepath.Join(t.TempDir(), "duplicate-feeds.sqlite3")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	_, err = db.Exec(`
CREATE TABLE feeds (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, url TEXT NOT NULL,
 enabled INTEGER NOT NULL DEFAULT 1, last_success TEXT, last_error TEXT
);
CREATE TABLE catalog_entries (
 feed_id INTEGER NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
 category TEXT NOT NULL, service TEXT NOT NULL, cidr TEXT NOT NULL,
 PRIMARY KEY (feed_id, category, service, cidr)
);
INSERT INTO feeds(id, name, url) VALUES
 (1, 'old-name', 'https://example.test/feed'),
 (2, 'new-name', 'https://example.test/feed');
INSERT INTO catalog_entries VALUES
 (1, 'one', 'a', '192.0.2.0/24'),
 (2, 'two', 'b', '198.51.100.0/24');
`)
	if err != nil {
		t.Fatal(err)
	}
	db.Close() //nolint:errcheck,gosec // test cleanup

	s, err := Open(path, false, "", false)
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	var feedCount int
	if err := s.DB.QueryRow("SELECT COUNT(*) FROM feeds WHERE url = 'https://example.test/feed'").
		Scan(&feedCount); err != nil {
		t.Fatal(err)
	}
	if feedCount != 1 {
		t.Fatalf("feeds=%d, want 1", feedCount)
	}
	// Migration 32 drops catalog entry data (regenerated by feed sync), but
	// the categories that migration 4 preserved must have made it into the
	// dictionary seed — both duplicate feeds' entries survived to that point.
	var categoryCount int
	if err := s.DB.QueryRow("SELECT COUNT(*) FROM categories WHERE name IN ('one', 'two')").
		Scan(&categoryCount); err != nil {
		t.Fatal(err)
	}
	if categoryCount != 2 {
		t.Fatalf("seeded categories=%d, want 2 (catalog lost before migration 32?)", categoryCount)
	}
}
